<?php

########################################################################
# Extension Manager/Repository config file for ext: "dam"
#
# Auto generated by Extension Builder 2011-09-08
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'DAM',
	'description' => 'Digital Asset Management for TYPO3.',
	'category' => 'plugin',
	'author' => 'The DAM development team',
	'author_email' => 'typo-project-dam@lists.typo3.org',
	'author_company' => 'TYPO3 Association',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>